# Generated by Django 4.0.1 on 2022-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
